name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Run tests with coverage
        run: yarn test --coverage

      - name: Store coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov-report

      - name: Retrieve coverage report artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage-report

      - name: Extract coverage data
        run: |
          coverageFile=./path/to/your/coverage-report.json
          coverageData=$(cat "$coverageFile" | jq -r '.total')
          coveragePercent=$(echo "$coverageData" | jq -r '.percentage')

          echo "::set-output name=coveragePercent::$coveragePercent"

      - name: Display coverage table in comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {repo, owner} = context.repo
            const coveragePercent = '${{ steps.extract-coverage-data.outputs.coveragePercent }}';

            const {number} = context.payload.pull_request;

            const commentBody = `
              ## Coverage Report
              
              | Coverage |
              |----------|
              | ${coveragePercent}% |
            `;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: commentBody,
            });