name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests and capture results
        id: unit-test-results
        run: |
          yarn test --json > test-results.json
          echo "::set-output name=results::$(cat test-results.json)"

      - name: Post test results
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('test-results.json', 'utf8');
            const { number } = context.payload.pull_request;

            const prNumber = number || context.payload.pull_request.number;

            console.log('ccccc number : ', number)
            console.log('ccccc owner : ', context.repo.owner)
            console.log('ccccc repo : ', context.repo.repo)

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: 'Test Results:\n```\n' + results + '\n```',
              });