name: Unit Tests
on:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run Jest
        run: npm run test -- --coverage
      - name: Get coverage
        run: |
          echo "::set-output name=coverage::$(npx jest --coverage)"
      - name: Post coverage comment
        uses: github-comment-action@v1
        with:
          comment: |
            **Code Coverage**

            The code coverage for this pull request is:

            * Lines: ${{ steps.get-coverage.outputs.coverage.lines }}%
            * Statements: ${{ steps.get-coverage.outputs.coverage.statements }}%
            * Branches: ${{ steps.get-coverage.outputs.coverage.branches }}%
            * Functions: ${{ steps.get-coverage.outputs.coverage.functions }}%
